In [1]:
import pprint
import numpy as np

In [2]:
def mult_matrix(M, N):

    return [[sum(el_m * el_n for el_m, el_n in zip(row_m, col_n)) for col_n in N] for row_m in M]

## To Find Pivot Matrix

In [3]:
def pivot_matrix(M):
    m = len(M)

    id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

    for j in range(m):
        row = max(range(j, m), key=lambda i: abs(M[i][j]))
        if j != row:
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return id_mat

## LUP Decomposition

In [4]:
def lu_decomposition(A):
    n = len(A)

    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]

    P = pivot_matrix(A)
    PA = mult_matrix(P, A)

    for j in range(n):
        L[j][j] = 1.0

        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = PA[i][j] - s1

        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (PA[i][j] - s2) / U[j][j]

    return (P, L, U)

In [5]:
A = [[2.0, 4.0, 1.0], [4.0, -10.0, 2.0], [1.0, 2.0, 4.0]]
B = [[5.0, 0.0, 0.0], [-8.0, 0.0, 0.0], [13.0, 0.0, 0.0]]
P, L, U = lu_decomposition(A)

print ("A:")
pprint.pprint(A)

print ("P:")
pprint.pprint(P)

print ("L:")
pprint.pprint(L)

print ("U:")
pprint.pprint(U)

A:
[[2.0, 4.0, 1.0], [4.0, -10.0, 2.0], [1.0, 2.0, 4.0]]
P:
[[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]]
L:
[[1.0, 0.0, 0.0], [0.5, 1.0, 0.0], [0.25, 0.5, 1.0]]
U:
[[4.0, -10.0, 2.0], [0.0, 9.0, 0.0], [0.0, 0.0, 3.5]]


## Forward Substitution (LY = PB)

In [6]:
def forward_substitution(B, L):
    n = len(L)
    Y = [[0.0] * n for i in range(n)]
    
    for j in range(n):
        Y[0][j] = B[0][j] / L[0][0]
        
        for i in range(1, n):
            sum = 0
            
            for k in range(0, i):
                sum = sum + L[i][k] * Y[k][j]
            Y[i][j] = (B[i][j] - sum) / L[i][i]
            
    return Y

In [7]:
Y = forward_substitution(np.dot(P, B), L)

print ("Y:")
pprint.pprint(Y)

Y:
[[-8.0, 0.0, 0.0], [9.0, 0.0, 0.0], [10.5, 0.0, 0.0]]


## Backward Substitution (UX = Y)

In [8]:
def backward_substitution(Y, U):
    n = len(U)
    X = [[0.0] * n for i in range(n)]
    
    for j in range(n):
        X[n-1][j] = Y[n-1][j] / U[n-1][n-1]
        
        for i in range(n-2, -1, -1):
            sum = 0
            
            for k in range(i+1, n):
                sum = sum + U[i][k] * X[k][j]
            X[i][j] = (Y[i][j] - sum) / U[i][i]
            
    return X

In [9]:
X = backward_substitution(Y, U)

print ("X:")
pprint.pprint(X)

X:
[[-1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [3.0, 0.0, 0.0]]


## Verifying Conditions

In [10]:
np.dot(L,Y) == np.dot(P,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
np.dot(U,X) == Y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
np.dot(A,X) == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])